export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Services } from "./Services";
export { default as AllergyAdvice } from "./AllergyAdvice";
export { default as Menu } from "./Menu";
export { default as MenuDetail } from "./MenuDetail";
export { default as PageNotFound } from "./PageNOtFound";
export { default as Cart } from "./Cart";
